[project]
name = "webdevops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "appdirs>=1.4.4",
    "backpack>=0.1",
    "cleo<0.7.0",
    "cloudpickle>=3.1.1",
    "configparser>=7.2.0",
    "doit==0.29.0",
    "funcsigs>=1.0.2",
    "graphviz>=0.4.10",
    "jinja2>=2.8",
    "markupsafe>=3.0.2",
    "mock>=5.2.0",
    "packaging>=24.2",
    "pbr>=6.1.1",
    "psutil>=7.0.0",
    "py>=1.11.0",
    "pylev>=1.4.0",
    "pyparsing>=3.2.3",
    "pytest>=8.3.5",
    "pytest-rerunfailures>=1.0.0",
    "pytest-timeout>=1.0.0",
    "pyyaml>=6.0.2",
    "simplejson>=3.20.1",
    "six>=1.17.0",
    "termcolor>=1.1.0",
    "testinfra>=1.4.2",
    "yamlordereddictloader>=0.1.0",
]
